apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: netflix-app
        image: murshidtp/netflix-app:latest
        ports:
        - containerPort: 3000

